"""
This type stub file was generated by pyright.
"""

from typing import Any
from asgiref.sync import SyncToAsync


class DatabaseSyncToAsync(SyncToAsync):
    """
    SyncToAsync version that cleans up old database connections when it exits.
    """

    def thread_handler(self, loop: Any, *args: Any, **kwargs: Any) -> Any:
        ...


database_sync_to_async = DatabaseSyncToAsync
