"""
This type stub file was generated by pyright.
"""

from typing import Any


class BaseMiddleware:
    """
    Base class for implementing ASGI middleware. Inherit from this and
    override the setup() method if you want to do things before you
    get to.

    Note that subclasses of this are not self-safe; don't store state on
    the instance, as it serves multiple application instances. Instead, use
    scope.
    """

    def __init__(self, inner: Any) -> None:
        """
        Middleware constructor - just takes inner application.
        """
        ...

    async def __call__(self, scope: Any, receive: Any, send: Any) -> Any:
        """
        ASGI application; can insert things into the scope and run asynchronous
        code.
        """
        ...
