"""
This type stub file was generated by pyright.
"""

from typing import Any


def name_that_thing(thing: Any) -> Any:
    """
    Returns either the function/class path or just the object's repr
    """
    ...


async def await_many_dispatch(consumer_callables: Any, dispatch: Any) -> Any:
    """
    Given a set of consumer callables, awaits on them all and passes results
    from them to the dispatch awaitable as they come in.
    """
    ...
