"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Literal, TypedDict, TypeVar

from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from django.db.models.query import QuerySet
from rest_framework import permissions
from rest_framework.request import Request
from rest_framework.viewsets import GenericViewSet

_T = TypeVar('_T', bound=Model)


class _Statement(TypedDict):
    action: list[str]
    principal: list[str]
    effect: Literal['allow', 'deny']
    condition: list[str]


class AccessPolicy(permissions.BasePermission):
    statements: list[_Statement] = ...
    id: Any = ...
    group_prefix: str = ...
    id_prefix: str = ...

    def has_permission(self, request: Request, view: GenericViewSet) -> bool:
        ...

    def get_policy_statements(self, request: Request, view: GenericViewSet) -> List[_Statement]:
        ...

    def get_user_group_values(self, user: AbstractUser) -> List[str]:
        ...

    @classmethod
    def scope_queryset(cls, request: Request, qs: QuerySet[_T]) -> QuerySet[_T]:
        ...
