"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from ..consumer import AsyncConsumer, SyncConsumer

class WebsocketConsumer(SyncConsumer):
    """
    Base WebSocket consumer. Provides a general encapsulation for the
    WebSocket handling model that other applications can build on.
    """
    groups: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def websocket_connect(self, message: Any) -> Any:
        """
        Called when a WebSocket connection is opened.
        """
        ...
    
    def connect(self) -> None:
        ...
    
    def accept(self, subprotocol: str=...) -> Any:
        """
        Accepts an incoming socket
        """
        ...
    
    def websocket_receive(self, message: Any) -> Any:
        """
        Called when a WebSocket frame is received. Decodes it and passes it
        to receive().
        """
        ...
    
    def receive(self, text_data: Any=..., bytes_data: Any=...) -> Any:
        """
        Called with a decoded WebSocket frame.
        """
        ...
    
    def send(self, text_data: Optional[str]=..., bytes_data: Optional[bytes]=..., close: bool=...) -> None:
        """
        Sends a reply back down the WebSocket
        """
        ...
    
    def close(self, code: Optional[str]=...) -> None:
        """
        Closes the WebSocket from the server end
        """
        ...
    
    def websocket_disconnect(self, message: Any) -> Any:
        """
        Called when a WebSocket connection is closed. Base level so you don't
        need to call super() all the time.
        """
        ...
    
    def disconnect(self, code: Any) -> Any:
        """
        Called when a WebSocket connection is closed.
        """
        ...
    


class JsonWebsocketConsumer(WebsocketConsumer):
    """
    Variant of WebsocketConsumer that automatically JSON-encodes and decodes
    messages as they come in and go out. Expects everything to be text; will
    error on binary data.
    """
    def receive(self, text_data: Any=..., bytes_data: Any=..., **kwargs: Any) -> Any:
        ...
    
    def receive_json(self, content: Any, **kwargs: Any) -> Any:
        """
        Called with decoded JSON content.
        """
        ...
    
    def send_json(self, content: Any, close: Any=...) -> Any:
        """
        Encode the given content as JSON and send it to the client.
        """
        ...
    
    @classmethod
    def decode_json(cls, text_data: Any) -> Any:
        ...
    
    @classmethod
    def encode_json(cls, content: Any) -> Any:
        ...
    


class AsyncWebsocketConsumer(AsyncConsumer):
    """
    Base WebSocket consumer, async version. Provides a general encapsulation
    for the WebSocket handling model that other applications can build on.
    """
    groups: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    async def websocket_connect(self, message: Any) -> Any:
        """
        Called when a WebSocket connection is opened.
        """
        ...
    
    async def connect(self) -> Any:
        ...
    
    async def accept(self, subprotocol: Any=...) -> Any:
        """
        Accepts an incoming socket
        """
        ...
    
    async def websocket_receive(self, message: Any) -> Any:
        """
        Called when a WebSocket frame is received. Decodes it and passes it
        to receive().
        """
        ...
    
    async def receive(self, text_data: Any=..., bytes_data: Any=...) -> Any:
        """
        Called with a decoded WebSocket frame.
        """
        ...
    
    async def send(self, text_data: Any=..., bytes_data: Any=..., close: Any=...) -> Any:
        """
        Sends a reply back down the WebSocket
        """
        ...
    
    async def close(self, code: Any=...) -> Any:
        """
        Closes the WebSocket from the server end
        """
        ...
    
    async def websocket_disconnect(self, message: Any) -> Any:
        """
        Called when a WebSocket connection is closed. Base level so you don't
        need to call super() all the time.
        """
        ...
    
    async def disconnect(self, code: Any) -> Any:
        """
        Called when a WebSocket connection is closed.
        """
        ...
    


class AsyncJsonWebsocketConsumer(AsyncWebsocketConsumer):
    """
    Variant of AsyncWebsocketConsumer that automatically JSON-encodes and decodes
    messages as they come in and go out. Expects everything to be text; will
    error on binary data.
    """
    async def receive(self, text_data: Any=..., bytes_data: Any=..., **kwargs: Any) -> Any:
        ...
    
    async def receive_json(self, content: Any, **kwargs: Any) -> Any:
        """
        Called with decoded JSON content.
        """
        ...
    
    async def send_json(self, content: Any, close: Any=...) -> Any:
        """
        Encode the given content as JSON and send it to the client.
        """
        ...
    
    @classmethod
    async def decode_json(cls, text_data: Any) -> Any:
        ...
    
    @classmethod
    async def encode_json(cls, content: Any) -> Any:
        ...
    


