"""
This type stub file was generated by pyright.
"""

from typing import Any
from rest_framework import viewsets

"""
    This class helps provide control over which fields can be expanded when a
    collection is request via the list method.
"""
class FlexFieldsMixin(viewsets.GenericViewSet, object):
    permit_list_expands: list[str] = ...
    def get_serializer_context(self) -> dict[str, Any]:
        ...
    


class FlexFieldsModelViewSet(FlexFieldsMixin, viewsets.ModelViewSet):
    ...


